[package]
name = "conflink"
version = "0.1.0"
edition = "2021"
authors = ["Nadir Fejzic <nadirfejzo@gmail.com>"]
description = "Utility for easy file and directory symlinking"
repository = "https://github.com/nfejzic/conflink"
license = "Apache-2.0"

[dependencies]
